Repository dendro-naap/dendro-cli, pull requests merged in 2021-04, with the labels that each got.

#75 Automate printing of CloudWatch logs
  src/aws/cloudwatch/describeLogGroups.ts
  src/aws/cloudwatch/describeLogStreams.ts
  src/aws/cloudwatch/getLogEvents.ts
  src/aws/orchestrator/describeLogGroups.ts
  src/aws/orchestrator/describeLogStreams.ts
  src/aws/orchestrator/getLogEvents.ts
  src/aws/orchestrator/getLogs.ts
  src/aws/orchestrator/index.ts
  src/commands/logs.ts
  src/pages/api/logs.ts
Labels: enhancement

#74 CLI: `install-vector` command
  src/commands/install-vector.ts
Labels: Must have

#55 Fix Vector typos
  src/vector/.logs/host.cpu.vector.json
  src/vector/.logs/host.disk.vector.json
  src/vector/.logs/host.filesystem.vector.json
  src/vector/.logs/host.host.vector.json
  src/vector/.logs/host.load.vector.json
  src/vector/.logs/host.memory.vector.json
  src/vector/.logs/host.network.vector.json
  src/vector/.logs/mongo.log.vector.json
  src/vector/.logs/mongo.metrics.vector.json
  src/vector/.logs/mongo_log.log
  src/vector/.logs/nginx.metric.vector.json
  src/vector/.logs/nginx_access.log
  src/vector/.logs/nginx_access.vector.json
  src/vector/.logs/nginx_error.log
  src/vector/.logs/postgres.log.log
  src/vector/.logs/postgres.log.vector.json
  src/vector/.logs/postgres.metrics.vector.json
  src/vector/.logs/schema.md
  src/vector/configs/host.ts
  src/vector/configs/mongo.ts
  src/vector/configs/nginx.ts
  src/vector/configs/postgres.ts
Labels: bug
